---
- hosts: all
  become: true
  tasks:
  - name: Wait for /var/lib/dpkg/lock-frontend to be released   
    shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

  - name: Update the repository cache and install python3-dev dependency
    apt:
      name: python3-dev
      state: latest
      update_cache: yes

  - name: Wait for /var/lib/dpkg/lock-frontend to be released   
    shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

  - name: Onstall python3-pip
    apt:
      name: python3-pip
      state: latest

  - name: Install Jupyter
    become: yes
    pip:
      name: jupyter
      state: latest
