---
- name: 'Bootstrap server and Install Jupyter'
  hosts: default

  tasks:
    - name: Wait for /var/lib/dpkg/lock-frontend to be released   
      shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;
    
    - name: Update apt-get repo and cache
      apt: update_cache=yes
      become: yes

    - name: Wait for /var/lib/dpkg/lock-frontend to be released   
      shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

    - name: Install python pip
      become: yes
      environment: 
        REQUESTS_CA_BUNDLE=''
      apt:
        pkg:
          - python3
          - python3-dev
          - python3-pip

    - name: Install Jupyter
      become: yes
      pip:
        name: jupyter
        state: latest
